In [ ]:
%pip install kagglehub

In [ ]:
import kagglehub
path = kagglehub.dataset_download("sobhanmoosavi/us-accidents")

print("Path to dataset files:", path)

In [54]:
import polars as pl
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import os
import warnings
warnings.filterwarnings("ignore")

In [29]:
file_path="E:/data_analysis/accident"
file_name="US_Accidents.csv"
file=os.path.join(file_path , file_name)
df=pl.read_csv(file)

In [4]:
print(f"The head of data: {df.head(5)}")

The head of data: shape: (5, 46)
┌─────┬─────────┬──────────┬─────────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ ID  ┆ Source  ┆ Severity ┆ Start_Time  ┆ … ┆ Sunrise_Sun ┆ Civil_Twili ┆ Nautical_T ┆ Astronomic │
│ --- ┆ ---     ┆ ---      ┆ ---         ┆   ┆ set         ┆ ght         ┆ wilight    ┆ al_Twiligh │
│ str ┆ str     ┆ i64      ┆ str         ┆   ┆ ---         ┆ ---         ┆ ---        ┆ t          │
│     ┆         ┆          ┆             ┆   ┆ str         ┆ str         ┆ str        ┆ ---        │
│     ┆         ┆          ┆             ┆   ┆             ┆             ┆            ┆ str        │
╞═════╪═════════╪══════════╪═════════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ A-1 ┆ Source2 ┆ 3        ┆ 2016-02-08  ┆ … ┆ Night       ┆ Night       ┆ Night      ┆ Night      │
│     ┆         ┆          ┆ 05:46:00    ┆   ┆             ┆             ┆            ┆            │
│ A-2 ┆ Source2 ┆ 2        ┆ 2016-02-08  ┆ … ┆ Night       ┆ Night       ┆ Night      ┆ Day        │
│     ┆         ┆          ┆ 06:07:59    ┆   ┆             ┆             ┆            ┆            │
│ A-3 ┆ Source2 ┆ 2        ┆ 2016-02-08  ┆ … ┆ Night       ┆ Night       ┆ Day        ┆ Day        │
│     ┆         ┆          ┆ 06:49:27    ┆   ┆             ┆             ┆            ┆            │
│ A-4 ┆ Source2 ┆ 3        ┆ 2016-02-08  ┆ … ┆ Night       ┆ Day         ┆ Day        ┆ Day        │
│     ┆         ┆          ┆ 07:23:34    ┆   ┆             ┆             ┆            ┆            │
│ A-5 ┆ Source2 ┆ 2        ┆ 2016-02-08  ┆ … ┆ Day         ┆ Day         ┆ Day        ┆ Day        │
│     ┆         ┆          ┆ 07:39:07    ┆   ┆             ┆             ┆            ┆            │
└─────┴─────────┴──────────┴─────────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [5]:
print(df.describe())

shape: (9, 47)
┌────────────┬──────────┬─────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ ID       ┆ Source  ┆ Severity   ┆ … ┆ Sunrise_S ┆ Civil_Twi ┆ Nautical_ ┆ Astronomi │
│ ---        ┆ ---      ┆ ---     ┆ ---        ┆   ┆ unset     ┆ light     ┆ Twilight  ┆ cal_Twili │
│ str        ┆ str      ┆ str     ┆ f64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ght       │
│            ┆          ┆         ┆            ┆   ┆ str       ┆ str       ┆ str       ┆ ---       │
│            ┆          ┆         ┆            ┆   ┆           ┆           ┆           ┆ str       │
╞════════════╪══════════╪═════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 7728394  ┆ 7728394 ┆ 7.728394e6 ┆ … ┆ 7705148   ┆ 7705148   ┆ 7705148   ┆ 7705148   │
│ null_count ┆ 0        ┆ 0       ┆ 0.0        ┆ … ┆ 23246     ┆ 23246     ┆ 23246     ┆ 23246     │
│ mean       ┆ null     ┆ null    ┆ 2.212384   ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ std        ┆ null     ┆ null    ┆ 0.487531   ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ min        ┆ A-1      ┆ Source1 ┆ 1.0        ┆ … ┆ Day       ┆ Day       ┆ Day       ┆ Day       │
│ 25%        ┆ null     ┆ null    ┆ 2.0        ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 50%        ┆ null     ┆ null    ┆ 2.0        ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 75%        ┆ null     ┆ null    ┆ 2.0        ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ max        ┆ A-999999 ┆ Source3 ┆ 4.0        ┆ … ┆ Night     ┆ Night     ┆ Night     ┆ Night     │
└────────────┴──────────┴─────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [6]:
print("DataFrame shape:" , df.shape)
print("_*_*_*_*_*_*_*_*_*_*_*_*_*_")
print("DataFrame columns:" , df.columns)
print("_*_*_*_*_*_*_*_*_*_*_*_*_*_")
print("DataFrame schema:" , df.schema)
print("_*_*_*_*_*_*_*_*_*_*_*_*_*_")
print("DataFrame Nulls:" , df.null_count())

DataFrame shape: (7728394, 46)
_*_*_*_*_*_*_*_*_*_*_*_*_*_
DataFrame columns: ['ID', 'Source', 'Severity', 'Start_Time', 'End_Time', 'Start_Lat', 'Start_Lng', 'End_Lat', 'End_Lng', 'Distance(mi)', 'Description', 'Street', 'City', 'County', 'State', 'Zipcode', 'Country', 'Timezone', 'Airport_Code', 'Weather_Timestamp', 'Temperature(F)', 'Wind_Chill(F)', 'Humidity(%)', 'Pressure(in)', 'Visibility(mi)', 'Wind_Direction', 'Wind_Speed(mph)', 'Precipitation(in)', 'Weather_Condition', 'Amenity', 'Bump', 'Crossing', 'Give_Way', 'Junction', 'No_Exit', 'Railway', 'Roundabout', 'Station', 'Stop', 'Traffic_Calming', 'Traffic_Signal', 'Turning_Loop', 'Sunrise_Sunset', 'Civil_Twilight', 'Nautical_Twilight', 'Astronomical_Twilight']
_*_*_*_*_*_*_*_*_*_*_*_*_*_
DataFrame schema: Schema({'ID': String, 'Source': String, 'Severity': Int64, 'Start_Time': String, 'End_Time': String, 'Start_Lat': Float64, 'Start_Lng': Float64, 'End_Lat': String, 'End_Lng': String, 'Distance(mi)': Float64, 'Description': String, 'Street': String, 'City': String, 'County': String, 'State': String, 'Zipcode': String, 'Country': String, 'Timezone': String, 'Airport_Code': String, 'Weather_Timestamp': String, 'Temperature(F)': Float64, 'Wind_Chill(F)': Float64, 'Humidity(%)': Float64, 'Pressure(in)': Float64, 'Visibility(mi)': Float64, 'Wind_Direction': String, 'Wind_Speed(mph)': Float64, 'Precipitation(in)': Float64, 'Weather_Condition': String, 'Amenity': Boolean, 'Bump': Boolean, 'Crossing': Boolean, 'Give_Way': Boolean, 'Junction': Boolean, 'No_Exit': Boolean, 'Railway': Boolean, 'Roundabout': Boolean, 'Station': Boolean, 'Stop': Boolean, 'Traffic_Calming': Boolean, 'Traffic_Signal': Boolean, 'Turning_Loop': Boolean, 'Sunrise_Sunset': String, 'Civil_Twilight': String, 'Nautical_Twilight': String, 'Astronomical_Twilight': String})
_*_*_*_*_*_*_*_*_*_*_*_*_*_
DataFrame Nulls: shape: (1, 46)
┌─────┬────────┬──────────┬────────────┬───┬─────────────┬─────────────┬─────────────┬─────────────┐
│ ID  ┆ Source ┆ Severity ┆ Start_Time ┆ … ┆ Sunrise_Sun ┆ Civil_Twili ┆ Nautical_Tw ┆ Astronomica │
│ --- ┆ ---    ┆ ---      ┆ ---        ┆   ┆ set         ┆ ght         ┆ ilight      ┆ l_Twilight  │
│ u32 ┆ u32    ┆ u32      ┆ u32        ┆   ┆ ---         ┆ ---         ┆ ---         ┆ ---         │
│     ┆        ┆          ┆            ┆   ┆ u32         ┆ u32         ┆ u32         ┆ u32         │
╞═════╪════════╪══════════╪════════════╪═══╪═════════════╪═════════════╪═════════════╪═════════════╡
│ 0   ┆ 0      ┆ 0        ┆ 0          ┆ … ┆ 23246       ┆ 23246       ┆ 23246       ┆ 23246       │
└─────┴────────┴──────────┴────────────┴───┴─────────────┴─────────────┴─────────────┴─────────────┘

In [37]:
null_count=df.null_count()
missing_report=null_count.unpivot(variable_name="column_name" ,value_name="missing_value_count")
total_rows = df.height

missing_report = missing_report.with_columns([
    ((total_rows - pl.col("missing_value_count")) / total_rows * 100).alias("filling_factor_pct")
])

missing_report = missing_report.sort("filling_factor_pct")
print(missing_report)

shape: (46, 3)
┌───────────────────┬─────────────────────┬────────────────────┐
│ column_name       ┆ missing_value_count ┆ filling_factor_pct │
│ ---               ┆ ---                 ┆ ---                │
│ str               ┆ u32                 ┆ f64                │
╞═══════════════════╪═════════════════════╪════════════════════╡
│ End_Lat           ┆ 3402762             ┆ 55.970645          │
│ End_Lng           ┆ 3402762             ┆ 55.970645          │
│ Precipitation(in) ┆ 2203586             ┆ 71.487142          │
│ Wind_Chill(F)     ┆ 1999019             ┆ 74.134096          │
│ Wind_Speed(mph)   ┆ 571233              ┆ 92.608645          │
│ …                 ┆ …                   ┆ …                  │
│ Station           ┆ 0                   ┆ 100.0              │
│ Stop              ┆ 0                   ┆ 100.0              │
│ Traffic_Calming   ┆ 0                   ┆ 100.0              │
│ Traffic_Signal    ┆ 0                   ┆ 100.0              │
│ Turning_Loop      ┆ 0                   ┆ 100.0              │
└───────────────────┴─────────────────────┴────────────────────┘

In [36]:
filtered_report = missing_report.filter(pl.col("filling_factor_pct") < 70)

print(filtered_report)

shape: (2, 3)
┌─────────────┬─────────────────────┬────────────────────┐
│ column_name ┆ missing_value_count ┆ filling_factor_pct │
│ ---         ┆ ---                 ┆ ---                │
│ str         ┆ u32                 ┆ f64                │
╞═════════════╪═════════════════════╪════════════════════╡
│ End_Lat     ┆ 3402762             ┆ 55.970645          │
│ End_Lng     ┆ 3402762             ┆ 55.970645          │
└─────────────┴─────────────────────┴────────────────────┘

In [ ]:
excludes = ["ID","Source","Description","Timezone","Country" ,"End_Lat","End_Lng",
           "Zipcode","Weather_Condition",
           "Airport_Code","Weather_Timestamp",
           "Civil_Twilight","Nautical_Twilight", "Astronomical_Twilight"]
df_cleaned=df.drop(excludes)
print(df_cleaned.head(5))

<bound method DataFrame.head of shape: (7_728_394, 32)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Severity ┆ Start_Tim ┆ End_Time  ┆ Start_Lat ┆ … ┆ Traffic_C ┆ Traffic_S ┆ Turning_L ┆ Sunrise_S │
│ ---      ┆ e         ┆ ---       ┆ ---       ┆   ┆ alming    ┆ ignal     ┆ oop       ┆ unset     │
│ i64      ┆ ---       ┆ str       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│          ┆ str       ┆           ┆           ┆   ┆ bool      ┆ bool      ┆ bool      ┆ str       │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 3        ┆ 2016-02-0 ┆ 2016-02-0 ┆ 39.865147 ┆ … ┆ false     ┆ false     ┆ false     ┆ Night     │
│          ┆ 8         ┆ 8         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 05:46:00  ┆ 11:00:00  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2016-02-0 ┆ 2016-02-0 ┆ 39.928059 ┆ … ┆ false     ┆ false     ┆ false     ┆ Night     │
│          ┆ 8         ┆ 8         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 06:07:59  ┆ 06:37:59  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2016-02-0 ┆ 2016-02-0 ┆ 39.063148 ┆ … ┆ false     ┆ true      ┆ false     ┆ Night     │
│          ┆ 8         ┆ 8         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 06:49:27  ┆ 07:19:27  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 3        ┆ 2016-02-0 ┆ 2016-02-0 ┆ 39.747753 ┆ … ┆ false     ┆ false     ┆ false     ┆ Night     │
│          ┆ 8         ┆ 8         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 07:23:34  ┆ 07:53:34  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2016-02-0 ┆ 2016-02-0 ┆ 39.627781 ┆ … ┆ false     ┆ true      ┆ false     ┆ Day       │
│          ┆ 8         ┆ 8         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 07:39:07  ┆ 08:09:07  ┆           ┆   ┆           ┆           ┆           ┆           │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2        ┆ 2019-08-2 ┆ 2019-08-2 ┆ 34.00248  ┆ … ┆ false     ┆ false     ┆ false     ┆ Day       │
│          ┆ 3         ┆ 3         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 18:03:25  ┆ 18:32:01  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2019-08-2 ┆ 2019-08-2 ┆ 32.76696  ┆ … ┆ false     ┆ false     ┆ false     ┆ Day       │
│          ┆ 3         ┆ 3         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 19:11:30  ┆ 19:38:23  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2019-08-2 ┆ 2019-08-2 ┆ 33.77545  ┆ … ┆ false     ┆ false     ┆ false     ┆ Day       │
│          ┆ 3         ┆ 3         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 19:00:21  ┆ 19:28:49  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2019-08-2 ┆ 2019-08-2 ┆ 33.99246  ┆ … ┆ false     ┆ false     ┆ false     ┆ Day       │
│          ┆ 3         ┆ 3         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 19:00:21  ┆ 19:29:42  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2019-08-2 ┆ 2019-08-2 ┆ 34.13393  ┆ … ┆ false     ┆ false     ┆ false     ┆ Day       │
│          ┆ 3         ┆ 3         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 18:52:06  ┆ 19:21:31  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘>

In [42]:
df_cleaned=df_cleaned.unique()

In [44]:
print(df_cleaned.head(5))

shape: (5, 32)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Severity ┆ Start_Tim ┆ End_Time  ┆ Start_Lat ┆ … ┆ Traffic_C ┆ Traffic_S ┆ Turning_L ┆ Sunrise_S │
│ ---      ┆ e         ┆ ---       ┆ ---       ┆   ┆ alming    ┆ ignal     ┆ oop       ┆ unset     │
│ i64      ┆ ---       ┆ str       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│          ┆ str       ┆           ┆           ┆   ┆ bool      ┆ bool      ┆ bool      ┆ str       │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 3        ┆ 2016-06-2 ┆ 2016-06-2 ┆ 41.15377  ┆ … ┆ false     ┆ false     ┆ false     ┆ Day       │
│          ┆ 0         ┆ 0         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 15:18:43  ┆ 16:03:43  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2022-07-2 ┆ 2022-07-2 ┆ 32.804774 ┆ … ┆ false     ┆ false     ┆ false     ┆ Day       │
│          ┆ 7         ┆ 7         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 14:30:22  ┆ 16:06:22  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 3        ┆ 2020-03-2 ┆ 2020-03-2 ┆ 41.86224  ┆ … ┆ false     ┆ true      ┆ false     ┆ Day       │
│          ┆ 5         ┆ 5         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 17:03:35  ┆ 17:33:35  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2021-11-2 ┆ 2021-11-2 ┆ 37.844543 ┆ … ┆ false     ┆ false     ┆ false     ┆ Day       │
│          ┆ 9         ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 13:10:30  ┆ 13:40:05  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2020-11-1 ┆ 2020-11-1 ┆ 33.133445 ┆ … ┆ false     ┆ false     ┆ false     ┆ Night     │
│          ┆ 3         ┆ 4         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 22:23:00  ┆ 00:01:34  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [46]:
df_size=df_cleaned.estimated_size("gb")
print(df_size)

1.1806741934269667

In [47]:
categorical_columns=[col for col, dtype in df_cleaned.schema.items() if dtype == pl.Categorical]
print(f"Categorical columns in dataframe: {df_cleaned.select(categorical_columns)}" , "\n")
String_columns=[col for col, dtype in df_cleaned.schema.items() if dtype == pl.String]
print(f"String columns in dataframe: {df_cleaned.select(String_columns)}")

Categorical columns in dataframe: shape: (0, 0)
┌┐
╞╡
└┘

String columns in dataframe: shape: (7_606_833, 8)
┌────────────┬────────────┬────────────┬────────────┬────────────┬───────┬────────────┬────────────┐
│ Start_Time ┆ End_Time   ┆ Street     ┆ City       ┆ County     ┆ State ┆ Wind_Direc ┆ Sunrise_Su │
│ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---   ┆ tion       ┆ nset       │
│ str        ┆ str        ┆ str        ┆ str        ┆ str        ┆ str   ┆ ---        ┆ ---        │
│            ┆            ┆            ┆            ┆            ┆       ┆ str        ┆ str        │
╞════════════╪════════════╪════════════╪════════════╪════════════╪═══════╪════════════╪════════════╡
│ 2016-06-20 ┆ 2016-06-20 ┆ I-75 N     ┆ Van Buren  ┆ Hancock    ┆ OH    ┆ WSW        ┆ Day        │
│ 15:18:43   ┆ 16:03:43   ┆            ┆            ┆            ┆       ┆            ┆            │
│ 2022-07-27 ┆ 2022-07-27 ┆ Oak Lawn   ┆ Dallas     ┆ Dallas     ┆ TX    ┆ S          ┆ Day        │
│ 14:30:22   ┆ 16:06:22   ┆ Ave        ┆            ┆            ┆       ┆            ┆            │
│ 2020-03-25 ┆ 2020-03-25 ┆ State      ┆ Glen Ellyn ┆ DuPage     ┆ IL    ┆ S          ┆ Day        │
│ 17:03:35   ┆ 17:33:35   ┆ Route 53   ┆            ┆            ┆       ┆            ┆            │
│ 2021-11-29 ┆ 2021-11-29 ┆ Eastshore  ┆ Emeryville ┆ Alameda    ┆ CA    ┆ WNW        ┆ Day        │
│ 13:10:30   ┆ 13:40:05   ┆ Fwy W      ┆            ┆            ┆       ┆            ┆            │
│ 2020-11-13 ┆ 2020-11-14 ┆ CA-78 E    ┆ San Marcos ┆ San Diego  ┆ CA    ┆ E          ┆ Night      │
│ 22:23:00   ┆ 00:01:34   ┆            ┆            ┆            ┆       ┆            ┆            │
│ …          ┆ …          ┆ …          ┆ …          ┆ …          ┆ …     ┆ …          ┆ …          │
│ 2022-06-05 ┆ 2022-06-05 ┆ Alcoa Hwy  ┆ Knoxville  ┆ Knox       ┆ TN    ┆ SE         ┆ Day        │
│ 18:37:44   ┆ 21:21:09   ┆            ┆            ┆            ┆       ┆            ┆            │
│ 2021-10-19 ┆ 2021-10-19 ┆ Pasadena   ┆ Los        ┆ Los        ┆ CA    ┆ CALM       ┆ Day        │
│ 07:08:00   ┆ 09:20:00   ┆ Ave        ┆ Angeles    ┆ Angeles    ┆       ┆            ┆            │
│ 2016-07-11 ┆ 2016-07-11 ┆ GA-407 W   ┆ Ellenwood  ┆ DeKalb     ┆ GA    ┆ SW         ┆ Day        │
│ 12:10:47   ┆ 12:55:47   ┆            ┆            ┆            ┆       ┆            ┆            │
│ 2018-05-16 ┆ 2018-05-16 ┆ I-35 S     ┆ Stacy      ┆ Chisago    ┆ MN    ┆ WNW        ┆ Day        │
│ 18:59:05   ┆ 19:28:50   ┆            ┆            ┆            ┆       ┆            ┆            │
│ 2022-03-10 ┆ 2022-03-10 ┆ S Semoran  ┆ Orlando    ┆ Orange     ┆ FL    ┆ NW         ┆ Day        │
│ 15:57:06.0 ┆ 18:01:34.0 ┆ Blvd       ┆            ┆            ┆       ┆            ┆            │
│ 00000000   ┆ 00000000   ┆            ┆            ┆            ┆       ┆            ┆            │
└────────────┴────────────┴────────────┴────────────┴────────────┴───────┴────────────┴────────────┘

In [ ]:
from sklearn.preprocessing import LabelEncoder

labels=LabelEncoder()
encoded = labels.fit_transform(df_cleaned["Sunrise_Sunset"].to_list())

df_cleaned = df_cleaned.with_columns(
    pl.Series("Sunrise_Sunset", encoded)
)

print(labels.inverse_transform([0, 1]) , "\n")
print(df_cleaned.head(5))

['Day' 'Night']

shape: (5, 32)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Severity ┆ Start_Tim ┆ End_Time  ┆ Start_Lat ┆ … ┆ Traffic_C ┆ Traffic_S ┆ Turning_L ┆ Sunrise_S │
│ ---      ┆ e         ┆ ---       ┆ ---       ┆   ┆ alming    ┆ ignal     ┆ oop       ┆ unset     │
│ i64      ┆ ---       ┆ str       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│          ┆ str       ┆           ┆           ┆   ┆ bool      ┆ bool      ┆ bool      ┆ i64       │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 3        ┆ 2016-06-2 ┆ 2016-06-2 ┆ 41.15377  ┆ … ┆ false     ┆ false     ┆ false     ┆ 0         │
│          ┆ 0         ┆ 0         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 15:18:43  ┆ 16:03:43  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2022-07-2 ┆ 2022-07-2 ┆ 32.804774 ┆ … ┆ false     ┆ false     ┆ false     ┆ 0         │
│          ┆ 7         ┆ 7         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 14:30:22  ┆ 16:06:22  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 3        ┆ 2020-03-2 ┆ 2020-03-2 ┆ 41.86224  ┆ … ┆ false     ┆ true      ┆ false     ┆ 0         │
│          ┆ 5         ┆ 5         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 17:03:35  ┆ 17:33:35  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2021-11-2 ┆ 2021-11-2 ┆ 37.844543 ┆ … ┆ false     ┆ false     ┆ false     ┆ 0         │
│          ┆ 9         ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 13:10:30  ┆ 13:40:05  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2020-11-1 ┆ 2020-11-1 ┆ 33.133445 ┆ … ┆ false     ┆ false     ┆ false     ┆ 1         │
│          ┆ 3         ┆ 4         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 22:23:00  ┆ 00:01:34  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [56]:
df_cleaned_small=df_cleaned.with_columns([
    pl.col("Severity").cast(pl.Int8),
    pl.col("Sunrise_Sunset").cast(pl.Int8)]
)

In [ ]:
df_size2=df_cleaned_small.estimated_size("gb")
print(df_size2)

1.1126742605119944

In [6]:
df_parsed=df_cleaned_small.with_columns(
    [
        pl.col("Start_Time").str.to_datetime() ,
        pl.col("End_Time").str.to_datetime()
    ]
).with_columns(
    [
        pl.col("Start_Time").dt.weekday().alias("day_of_week")
    ]
)
df_parsed.head(5)

shape: (5, 33)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Severity ┆ Start_Tim ┆ End_Time  ┆ Start_Lat ┆ … ┆ Traffic_S ┆ Turning_L ┆ Sunrise_S ┆ day_of_we │
│ ---      ┆ e         ┆ ---       ┆ ---       ┆   ┆ ignal     ┆ oop       ┆ unset     ┆ ek        │
│ i8       ┆ ---       ┆ datetime[ ┆ f64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│          ┆ datetime[ ┆ μs]       ┆           ┆   ┆ bool      ┆ bool      ┆ i8        ┆ i8        │
│          ┆ μs]       ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2        ┆ 2016-06-2 ┆ 2016-06-2 ┆ 41.15377  ┆ … ┆ false     ┆ false     ┆ 0         ┆ 1         │
│          ┆ 0         ┆ 0         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 15:18:43  ┆ 16:03:43  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2022-07-2 ┆ 2022-07-2 ┆ 32.804774 ┆ … ┆ false     ┆ false     ┆ 0         ┆ 3         │
│          ┆ 7         ┆ 7         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 14:30:22  ┆ 16:06:22  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2020-03-2 ┆ 2020-03-2 ┆ 41.86224  ┆ … ┆ true      ┆ false     ┆ 0         ┆ 3         │
│          ┆ 5         ┆ 5         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 17:03:35  ┆ 17:33:35  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2021-11-2 ┆ 2021-11-2 ┆ 37.844543 ┆ … ┆ false     ┆ false     ┆ 0         ┆ 1         │
│          ┆ 9         ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 13:10:30  ┆ 13:40:05  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2020-11-1 ┆ 2020-11-1 ┆ 33.133445 ┆ … ┆ false     ┆ false     ┆ 1         ┆ 5         │
│          ┆ 3         ┆ 4         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 22:23:00  ┆ 00:01:34  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [19]:

format_days={1: "Mon", 2: "Tue", 3: "Wed", 4: "Thu", 5: "Fri", 6: "Sat", 7: "Sun"}
day_count = (
    df_parsed.group_by("day_of_week")    
    .agg(pl.len().alias("count"))         
    .sort("day_of_week")                   
    .with_columns(                         
        pl.col("day_of_week").cast(pl.String).replace(format_days)
    )
)

print(day_count)

shape: (7, 2)
┌─────────────┬─────────┐
│ day_of_week ┆ count   │
│ ---         ┆ ---     │
│ str         ┆ u32     │
╞═════════════╪═════════╡
│ Mon         ┆ 1192892 │
│ Tue         ┆ 1272547 │
│ Wed         ┆ 1292959 │
│ Thu         ┆ 1296216 │
│ Fri         ┆ 1347188 │
│ Sat         ┆ 654647  │
│ Sun         ┆ 550384  │
└─────────────┴─────────┘

In [20]:
fig1 = go.Figure(data=[
    go.Bar(
        x=day_count["day_of_week"], 
        y=day_count["count"],
        marker_color='teal'
    )
])
fig1.update_layout(title="Accidents by Day of Week", xaxis_title="Day", yaxis_title="Total Accidents")
fig1.show()

In [7]:
time_analysis=(
    df_parsed.with_columns(
    pl.col("Start_Time").dt.hour().alias("Hour")) 
    .group_by(["Hour", "Severity"])
    .agg(pl.len().alias("Severity_Count"))
    .sort("Hour")
)
severity_labels = {
        0: "Low",
        1: "Medium",
        2: "High"
    }
fig2 = go.Figure()
for sev_val, label in severity_labels.items():

    subset = time_analysis.filter(pl.col("Severity") == sev_val)
    
    fig2.add_trace(
            go.Bar(
                x=subset["Hour"],           
                y=subset["Severity_Count"], 
                name=label
            )
        )

fig2.update_layout(
    title="Distribution of Accidents by Hour and Severity",
    xaxis_title="Hour of Day (24H)",    
    yaxis_title="Number of Accidents",  
    barmode="stack", 
    #template="plotly_dark",
    legend_title="Severity Level",
    xaxis=dict(
        tickmode='linear',
        tick0=0,
        dtick=1
    )
)

fig2.show()

In [38]:
import plotly.express as px
dn_analysis = (
    df_parsed.with_columns(
        pl.col("Sunrise_Sunset").alias("D/N")
    )
    .group_by(["D/N", "Severity"])
    .agg(pl.len().alias("Severity_Count"))
    .sort("D/N")
)

severity_labels = {
    0: "Low",
    1: "Medium",
    2: "High"
}

colors = px.colors.qualitative.Prism

fig4 = go.Figure()

for i, (sev_val, label) in enumerate(severity_labels.items()):
    subset = dn_analysis.filter(pl.col("Severity") == sev_val)

    fig4.add_trace(
        go.Bar(
            x=subset["D/N"],
            y=subset["Severity_Count"],
            name=label,
            marker_color=colors[i % len(colors)]
        )
    )

fig4.update_layout(
    title="Distribution of Accidents by Daylight and Severity",
    xaxis_title="Day or Night",
    yaxis_title="Number of Accidents",
    barmode="stack",
    legend_title="Severity Level",
    xaxis=dict(
        tickmode="array",
        tickvals=[0, 1],
        ticktext=["day", "night"]
    )
)

fig4.show()

In [ ]:
state_analysis=(
    df_parsed.with_columns(
    pl.col("State").alias("State")) 
    .group_by(["State", "Severity"])
    .agg(pl.len().alias("Severity_Count"))
    .sort("State")
)
severity_labels = {
        0: "Low",
        1: "Medium",
        2: "High"
    }
fig3 = go.Figure()
for sev_val, label in severity_labels.items():

    subset = state_analysis.filter(pl.col("Severity") == sev_val)
    
    fig3.add_trace(
            go.Bar(
                x=subset["State"],           
                y=subset["Severity_Count"], 
                name=label
            )
        )

fig3.update_layout(
    title="Distribution of Accidents by State and Severity",
    xaxis_title="States",    
    yaxis_title="Number of Accidents",  
    barmode="stack", 
    #template="plotly_dark",
    legend_title="Severity Level",
    xaxis=dict(
        tickmode='linear',
        tick0=0,
        dtick=1
    )
)

fig3.show()

In [42]:
top_city_acc=(df_parsed.group_by("State").
              agg(pl.col("Severity").count().alias("ACC_count"))
              ).sort(by="ACC_count", descending=True)

In [43]:
top_city_acc.head(5)

shape: (5, 2)
┌───────┬───────────┐
│ State ┆ ACC_count │
│ ---   ┆ ---       │
│ str   ┆ u32       │
╞═══════╪═══════════╡
│ CA    ┆ 1717732   │
│ FL    ┆ 867276    │
│ TX    ┆ 578020    │
│ SC    ┆ 379652    │
│ NY    ┆ 338422    │
└───────┴───────────┘

In [49]:
df_parsed[: , 18:31].null_count()

shape: (1, 13)
┌─────────┬──────┬──────────┬──────────┬───┬──────┬────────────────┬────────────────┬──────────────┐
│ Amenity ┆ Bump ┆ Crossing ┆ Give_Way ┆ … ┆ Stop ┆ Traffic_Calmin ┆ Traffic_Signal ┆ Turning_Loop │
│ ---     ┆ ---  ┆ ---      ┆ ---      ┆   ┆ ---  ┆ g              ┆ ---            ┆ ---          │
│ u32     ┆ u32  ┆ u32      ┆ u32      ┆   ┆ u32  ┆ ---            ┆ u32            ┆ u32          │
│         ┆      ┆          ┆          ┆   ┆      ┆ u32            ┆                ┆              │
╞═════════╪══════╪══════════╪══════════╪═══╪══════╪════════════════╪════════════════╪══════════════╡
│ 0       ┆ 0    ┆ 0        ┆ 0        ┆ … ┆ 0    ┆ 0              ┆ 0              ┆ 0            │
└─────────┴──────┴──────────┴──────────┴───┴──────┴────────────────┴────────────────┴──────────────┘

In [56]:
cols_to_analyze = [
    "Amenity", "Bump", "Crossing", "Give_Way", "Junction", 
    "No_Exit", "Railway", "Roundabout", "Station", "Stop", 
    "Traffic_Calming", "Traffic_Signal", "Turning_Loop"
]

states = ["CA", "FL", "TX", "SC", "NY"]

fig = make_subplots(
    rows=5, cols=1, 
    shared_xaxes=True, 
    vertical_spacing=0.05,
    subplot_titles=states
)

for idx, state in enumerate(states):
    df_state = df_parsed.filter(pl.col("State") == state).select(cols_to_analyze)
    
    if df_state.height == 0:
        continue

    analysis_data = []
    for col in cols_to_analyze:
        occurrence_rate = df_state[col].mean() * 100
        analysis_data.append({
            "Feature": col.replace("_", " ").title(),
            "Rate": occurrence_rate
        })
    
    summary_df = pl.DataFrame(analysis_data).sort("Rate")
    

    rates = summary_df["Rate"].to_list()
    features = summary_df["Feature"].to_list()
    labels = summary_df["Rate"].map_elements(lambda x: f"{x:.1f}%", return_dtype=pl.Utf8).to_list()

    fig.add_trace(
        go.Bar(
            x=rates,
            y=features,
            orientation='h',
            text=labels,
            textposition='outside',
            marker=dict(color=rates, colorscale='Viridis'),
            showlegend=False
        ),
        row=idx+1, col=1
    )

fig.update_layout(
    height=1500, 
    width=1000, 
    title_text="Traffic Feature Prevalence by State",
    template="plotly_white",
    showlegend=False
)

fig.update_xaxes(title_text="Percentage (%)")
fig.show()

In [ ]:
df_parsed.write_csv("acc_cleaned.csv")
df_parsed.write_parquet("acc_cleaned.parquet")